export const FETCH_SMURFS = "FETCH_SMURFS";
export const FETCH_SMURFS_SUCCESS = "FETCH_SMURFS_SUCCESS";
export const FETCH_SMURFS_FAILURE = "FETCH_SMURFS_FAILURE";
export const ADD_SMURF = "ADD_SMURF";
export const ADD_SMURF_SUCCESS = "ADD_SMURF_SUCCES";
export const ADD_SMURF_FAILURE = "ADD_SMURF_FAILURE";
export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
